---
- import_playbook: pbInstallDocker.yml
- import_playbook: pbPreCheck.yml
- import_playbook: pbAwsUpdatePassword.yml
- import_playbook: pbInitCluster.yml
- import_playbook: pbSystemConfig.yml
- import_playbook: pbCloudConnectUser.yml
- import_playbook: pbSe.yml
- import_playbook: pbDnsIpam.yml
- import_playbook: pbCloudLsc.yml
- import_playbook: pbCloudVmw.yml
- import_playbook: pbCloudOpenstack.yml
- import_playbook: pbCloudGcp.yml
- import_playbook: pbCloudAzure.yml
- import_playbook: pbCloudAws.yml
- import_playbook: pbCloudNsxt.yml
- import_playbook: pbCloudNoAccess.yml
- import_playbook: pbCloudCheck.yml
- import_playbook: pbApplicationProfile.yml
- import_playbook: pbSeGroup.yml
- import_playbook: pbVsLsc.yml
- import_playbook: pbVsVipAzure.yml
- import_playbook: pbVsVipAws.yml
- import_playbook: pbVsVipGcp.yml
- import_playbook: pbVsVmw.yml
- import_playbook: pbVsNsx.yml
- import_playbook: pbVsVipNoAccessVmware.yml
- import_playbook: pbVs.yml
- import_playbook: pbGslb.yml
- import_playbook: pbGslbService.yml
