---
- hosts: controller
  gather_facts: no
  become_user: root
  become_method: sudo

  tasks:

    - name: Setting up admin password
      command: "{{ item }}"
      ignore_errors: no
      tags:
        - admin
      with_items:
        - sudo /opt/avi/scripts/initialize_admin_user.py --password "{{ controller.password }}"
      when:
        - controller.environment == "AWS"
