---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Defining SE Memory
      set_fact:
        seMem: "{{ lsc.serviceEngineGroup.memory_per_se / 1000 }}"
      when:
        - lsc is defined
      tags:
        - cloud

    - name: Defining SE Memory
      set_fact:
        seMemG: "{{ seMem | float | round(0,'common') | int }}"
      when:
        - lsc is defined
      tags:
        - cloud

    - name: Defining SE structure
      set_fact:
        listSe: "{{ listSe | default([]) + [{ 'host_attr': [{'attr_key': 'CPU', 'attr_val': lsc.serviceEngineGroup.vcpus_per_se }, {'attr_key': 'MEMORY', 'attr_val': seMemG}, {'attr_key': 'DPDK', 'attr_val': lsc.serviceEngineGroup.DPDK }, {'attr_key': 'SE_INBAND_MGMT', 'attr_val': lsc.serviceEngineGroup.SE_INBAND_MGMT }], 'host_ip': {'type': 'V4', 'addr': item }, 'se_group_ref': '/api/serviceenginegroup/?name=Default-Group'} ] }}"
      loop: "{{ seLsc }}"
      when:
        - lsc is defined
      tags:
        - cloud

    - name: Debug
      debug:
        msg: "{{ listSe }}"
      when:
        - lsc is defined
      tags:
        - debug

    - name: Creating Linux Server Cloud
      avi_cloud:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        vtype: CLOUD_LINUXSERVER
        license_tier: ENTERPRISE_18
        enable_vip_static_routes: false
        ip6_autocfg_enabled: false
        dhcp_enabled: false
        linuxserver_configuration:
          se_sys_disk_size_GB: 10
          se_log_disk_size_GB: 5
          se_inband_mgmt: false
          hosts: '{{ listSe }}'
          ssh_user_ref: /api/cloudconnectoruser/?name=credsLsc
        prefer_static_routes: false
        license_type: LIC_CORES
        mtu: 1500
        apic_mode: false
        state_based_dns_registration: true
        name: "{{ lsc.name }}"
      when:
        - lsc is defined
      tags:
        - cloud