---
- hosts: localhost
  connection: local
  gather_facts: no


  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: sleep for 180 seconds and continue with play (for Azure and OpenStack)
      wait_for: timeout=180
      when:
        - azure is defined or openstack is defined
      tags:
        - cloud

    - name: sleep for 120 seconds and continue with play
      wait_for: timeout=120
      when:
        - azure is defined or aws is defined or gcp is defined or nsxt is defined or vmw is defined or openstack is defined
      tags:
        - cloud

    - name: Wait for the cloud 0 to be ready // this is expected to fail for vmc
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        path: cloud-inventory
      register: cloudStatusResults
      until: 'cloudStatusResults.obj.results.0.status.se_image_state.0.state == "IMG_GEN_COMPLETE"'
      retries: 60
      delay: 30
      ignore_errors: yes

    - name: Wait for the cloud 1 to be ready // this is expected to fail for vmc
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        path: cloud-inventory
      register: cloudStatusResults
      until: 'cloudStatusResults.obj.results.1.status.se_image_state.0.state == "IMG_GEN_COMPLETE"'
      retries: 60
      delay: 30
      ignore_errors: yes

    - name: Debug
      debug:
        msg: "{{ cloudStatusResults }}"
      tags:
        - debug

    - name: Wait for the cloud 2 to be ready // this is expected to fail for vmc
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        path: cloud-inventory
      register: cloudStatusResults
      until: 'cloudStatusResults.obj.results.2.status.se_image_state.0.state == "IMG_GEN_COMPLETE"'
      retries: 60
      delay: 30
      ignore_errors: yes
