---
- hosts: localhost
  connection: local
  gather_facts: no

  # vars_files:
  #   - "../vars/fromTerraform.yml"

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug
      when:
        - nsxt is defined

    - name: Create a Cloud connector user for NSX-T
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: credsNsxt
        nsxt_credentials:
          username: "{{ nsx.username }}"
          password: "{{ nsx.password }}"
      register: nsxtUserOutput
      tags:
        - cloud
      when:
        - nsxt is defined

    - name: Create a Cloud connector user for NSX-T (vcenter)
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: credsVcenter
        vcenter_credentials:
          username: "{{ vcenter.username }}"
          password: "{{ vcenter.password }}"
      register: vcenterUserOutput
      tags:
        - cloud
        - vcenter
      when:
        - nsxt is defined

    - name: Debug
      debug:
        msg: "{{ nsxtUserOutput.obj.uuid }}"
      tags:
        - debug
      when:
        - nsxt is defined

    - name: Debug
      debug:
        msg: "{{ vcenterUserOutput.obj.uuid }}"
      tags:
        - debug
      when:
        - nsxt is defined

    - name: Create a Cloud connector user for Azure
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ azure.cloud_credentials_ref }}"
        azure_serviceprincipal:
          tenant_id: "{{ azure.tenant_id }}"
          application_id: "{{ azure.application_id }}"
          authentication_token: "{{ azure.authentication_token }}"
      tags:
        - cloud
      when:
        - azure is defined
