---
- hosts: localhost
  connection: local
  gather_facts: no

  # vars_files:
  #   - "../vars/fromTerraform.yml"

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug
      when:
        - nsxt is defined

    - name: Create a Cloud connector user for NSX-T
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: credsNsxt
        nsxt_credentials:
          username: "{{ nsxt.username }}"
          password: "{{ nsxt.password }}"
      register: nsxtUserOutput
      tags:
        - cloud
      when:
        - nsxt is defined

    - name: Create a Cloud connector user for NSX-T (vcenter)
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: credsVcenter
        vcenter_credentials:
          username: "{{ vcenter.username }}"
          password: "{{ vcenter.password }}"
      register: vcenterUserOutput
      tags:
        - cloud
        - vcenter
      when:
        - nsxt is defined

    - name: Debug
      debug:
        msg: "{{ nsxtUserOutput.obj.uuid }}"
      tags:
        - debug
      when:
        - nsxt is defined

    - name: Debug
      debug:
        msg: "{{ vcenterUserOutput.obj.uuid }}"
      tags:
        - debug
      when:
        - nsxt is defined
