---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug
      when:
        - nsxt is defined or lsc is defined

    - name: Create a Cloud connector user for LSC
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        private_key: "{{ lookup('file', '{{ lsc.serviceEngineGroup.private_key_path }}') }}"
        name: credsLsc
      register: lscUserOutput
      ignore_errors: no
      tags:
        - cloud
      when:
        - lsc is defined

    - name: Debug
      debug:
        msg: "{{ lscUserOutput.obj.uuid }}"
      tags:
        - debug
      when:
        - lsc is defined

    - name: Create a Cloud connector user for NSX-T
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: credsNsxt
        nsxt_credentials:
          username: "{{ nsx_username }}"
          password: "{{ nsx_password }}"
      register: nsxtCredsOutput
      tags:
        - cloud
      when:
        - nsxt is defined
        - nsx_username is defined
        - nsx_password is defined

    - name: Debug
      debug:
        msg: "{{ vcenter_credentials }}"
      tags:
        - debug

    - name: Create a Cloud connector user for NSX-T (vcenter)
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "creds-vcenter-{{ my_idx }}"
        vcenter_credentials:
          username: "{{ item.username }}"
          password: "{{ item.password }}"
      loop: "{{ vcenter_credentials.vcenter_credentials }}"
      loop_control:
        index_var: my_idx
      register: vcenterCredsOutput
      tags:
        - cloud
      when:
        - nsxt is defined
        - vcenter_credentials is defined

    - name: Saving vCenter Creds uuid in a list - NSX-T
      set_fact:
        vcenterCreds: "{{ vcenterCreds | default([]) + [item.obj.uuid | from_json] }}"
      loop: "{{ vcenterCredsOutput.results }}"
      when:
        - vcenterCredsOutput.results is defined

    - name: Saving NSXT Creds uuid - NSX-T
      set_fact:
        nsxtCredsUuid: "{{ nsxtCredsOutput.obj.uuid }}"
      loop: "{{ vcenterCredsOutput.results }}"
      when:
        - vcenterCredsOutput.results is defined

    - name: Debug
      debug:
        msg: "{{ nsxtCredsUuid }}"
      tags:
        - debug
      when:
        - nsxtCredsUuid is defined

    - name: Debug
      debug:
        msg: "{{ vcenterCreds }}"
      tags:
        - debug
      when:
        - vcenterCreds is defined
