---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug
      when:
        - nsxt is defined or lsc is defined

    - name: Create a Cloud connector user for LSC
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        private_key: "{{ lookup('file', '{{ lsc.serviceEngineGroup.private_key_path }}') }}"
        name: credsLsc
      register: lscUserOutput
      ignore_errors: no
      tags:
        - cloud
      when:
        - lsc is defined

    - name: Debug
      debug:
        msg: "{{ lscUserOutput.obj.uuid }}"
      tags:
        - debug
      when:
        - lsc is defined

    - name: Create a Cloud connector user for NSX-T
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: credsNsxt
        nsxt_credentials:
          username: "{{ nsx_user }}"
          password: "{{ nsx_password }}"
      register: nsxtUserOutput
      tags:
        - cloud
      when:
        - nsxt is defined
        - nsx_user is defined
        - nsx_password is defined

    - name: Create a Cloud connector user for NSX-T (vcenter)
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: credsVcenter
        vcenter_credentials:
          username: "{{ nsx_vsphere_user }}"
          password: "{{ nsx_vsphere_password }}"
      register: vcenterUserOutput
      tags:
        - cloud
      when:
        - nsxt is defined
        - nsx_vsphere_user is defined
        - nsx_vsphere_password is defined

    - name: Debug
      debug:
        msg: "{{ nsxtUserOutput.obj.uuid }}"
      tags:
        - debug
      when:
        - nsxt is defined

    - name: Debug
      debug:
        msg: "{{ vcenterUserOutput.obj.uuid }}"
      tags:
        - debug
      when:
        - nsxt is defined
