---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    listNetworkUuid: []

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: python workaround to retrieve transport zone id - NSXT
      command: python3 python/retrieveNsxtTransportZoneId.py "{{ controller.aviCredsJsonFile }}" "{{ nsxt.server }}" "{{ nsxtUserOutput.obj.uuid }}" "{{ nsxt.transport_zone.name }}"
      ignore_errors: no
      register: nsxtTransportZoneId
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.transport_zone.name is defined
        - nsxt.server is defined

    - name: python workaround to retrieve tier1s for mgt - NSXT
      command: python3 python/retrieveNsxtTier1s.py "{{ controller.aviCredsJsonFile }}" "{{ nsxt.server }}" "{{ nsxtUserOutput.obj.uuid }}" "{{ nsxt.management_network.tier1 }}"
      ignore_errors: no
      register: nsxtTier1sMgtJson
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.management_network.tier1 is defined
        - nsxt.server is defined

    - set_fact:
        nsxtTier1sMgt: "{{ nsxtTier1sMgtJson.stdout | from_json }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.management_network.tier1 is defined
        - nsxt.server is defined

    - name: python workaround to retrieve tier1s for avi vip - NSXT
      command: python3 python/retrieveNsxtTier1s.py "{{ controller.aviCredsJsonFile }}" "{{ nsxt.server }}" "{{ nsxtUserOutput.obj.uuid }}" "{{ nsxt.network_vip.tier1 }}"
      ignore_errors: no
      register: nsxtTier1sVipJson
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.network_vip is defined
        - nsxt.server is defined


    - set_fact:
        nsxtTier1sVip: "{{ nsxtTier1sVipJson.stdout | from_json }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.network_vip is defined
        - nsxt.server is defined

    - name: python workaround to retrieve segment details for avi management - NSXT
      command: python3 python/retrieveNsxtSegment.py "{{ controller.aviCredsJsonFile }}" "{{ nsxt.server }}" "{{ nsxtUserOutput.obj.uuid }}" "{{ nsxtTransportZoneId.stdout }}" "{{ nsxt.management_network.name }}"
      ignore_errors: no
      register: nsxtSegmentMgtJson
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.server is defined
        - nsxt.management_network.name is defined

    - set_fact:
        nsxtSegmentMgt: "{{ nsxtSegmentMgtJson.stdout | from_json }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.server is defined
        - nsxt.management_network.name is defined

    - name: python workaround to retrieve segment details for avi vip - NSXT
      command: python3 python/retrieveNsxtSegment.py "{{ controller.aviCredsJsonFile }}" "{{ nsxt.server }}" "{{ nsxtUserOutput.obj.uuid }}" "{{ nsxtTransportZoneId.stdout }}" "{{ nsxt.network_vip.name }}"
      ignore_errors: no
      register: nsxtSegmentVipJson
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.network_vip.name is defined
        - nsxt.server is defined

    - set_fact:
        nsxtSegmentVip: "{{ nsxtSegmentVipJson.stdout | from_json }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.network_vip.name is defined
        - nsxt.server is defined

    - name: python workaround to retrieve segment details for avi backend network - NSXT
      command: python3 python/retrieveNsxtSegment.py "{{ controller.aviCredsJsonFile }}" "{{ nsxt.server }}" "{{ nsxtUserOutput.obj.uuid }}" "{{ nsxtTransportZoneId.stdout }}" "{{ nsxt.network_backend.name }}"
      ignore_errors: no
      register: nsxtSegmentBacJson
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.network_backend.name is defined
        - nsxt.server is defined

    - set_fact:
        nsxtSegmentBac: "{{ nsxtSegmentBacJson.stdout | from_json }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.network_backend.name is defined
        - nsxt.server is defined

    - name: Configure Avi Cloud for NSXT - NSXT
      avi_cloud:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ nsxt.name}}"
        vtype: CLOUD_NSXT
        nsxt_configuration:
          nsxt_url: "{{ nsxt.server }}"
          transport_zone: "{{ nsxtTransportZoneId.stdout }}"
          # site_id: default
          # enforcementpoint_id: default
          # domain_id: default
          management_segment:
            tier1_lr_id: "{{ nsxtTier1sMgt.id }}"
            segment_id: "{{ nsxtSegmentMgt.id }}"
          tier1_segment_config:
            segment_config_mode: TIER1_SEGMENT_MANUAL
            manual:
              tier1_lrs:
                - tier1_lr_id: "{{ nsxtTier1sVip.id }}"
                  segment_id: "{{ nsxtSegmentVip.id }}"
          #automate_dfw_rules: false
          nsxt_credentials_ref: "/api/cloudconnectoruser/{{ nsxtUserOutput.obj.uuid }}"
        dhcp_enabled: "{{ nsxt.dhcp_enabled }}"
        dns_provider_ref: "/api/ipamdnsproviderprofile/?name={{ nsxt.dns_provider_ref | default('dns-avi') }}"
        obj_name_prefix: "{{ nsxt.obj_name_prefix | default('AVINSXT') }}"
      register: output_cloud_nsxt
      when:
        - nsxt.name is defined
        - nsxt.server is defined
        - nsxt.dhcp_enabled is defined
        - nsxt.network_vip is defined
        - nsxt.management_network is defined
      tags:
        - cloud

    - set_fact:
        cloud_nsxt_uuid: "{{ output_cloud_nsxt.obj.uuid }}"
      when:
        - output_cloud_nsxt is defined
      tags:
        - cloud
        - nsxtApi

    - name: Debug
      debug:
        msg: "{{ cloud_nsxt_uuid }}"
      when:
        - output_cloud_nsxt is defined

    - pause:
        minutes: 1
      when:
        - nsxt is defined
      tags:
        - cloud

    - name: python workaround to retrieve vcenter content library info - NSXT
      command: python3 python/retrieveNsxtVcentersLibrary.py "{{ controller.aviCredsJsonFile }}" "{{ nsxt.vcenter.server }}" "{{ vcenterUserOutput.obj.uuid }}" "{{ nsxt.vcenter.content_library.name }}"
      ignore_errors: no
      register: vcenterContentLibraryJson
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.vcenter.content_library.name is defined
        - nsxt.vcenter.server is defined

    - set_fact:
        vcenterContentLibrary: "{{ vcenterContentLibraryJson.stdout | from_json }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.vcenter.content_library.name is defined
        - nsxt.vcenter.server is defined

    - name: Configure Vcenter Server for NSXT cloud - NSXT
      avi_vcenterserver:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: vcenterserverOne
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.name }}"
        vcenter_url: "{{ nsxt.vcenter.server }}"
        content_lib:
          id: "{{ vcenterContentLibrary.id }}"
        vcenter_credentials_ref: "/api/cloudconnectoruser/{{ vcenterUserOutput.obj.uuid }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.vcenter.server is defined
        - nsxt.vcenter.content_library.name is defined

    - pause:
        minutes: 1
      when:
        - nsxt is defined
      tags:
        - cloud

    - name: get Network details - NSXT
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        timeout: 300
        path: network
        params:
          page_size: -1
      register: networkOutput
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt is defined

    - name: Retrieve Network Mgt Uuid - NSXT
      set_fact:
        networkMgtUuid: "{{ item.uuid }}"
      loop: "{{ networkOutput.obj.results }}"
      loop_control:
        label: "{{ item.name }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt is defined
        - item.name == nsxt.management_network.name

    - name: Set IP details of Mgmt Network - NSXT
      set_fact:
        configured_subnets_mgmt:
          - prefix:
              mask: "{{ nsxt.management_network.cidr.split('/')[1] }}"
              ip_addr:
                type: "{{ nsxt.management_network.type }}"
                addr: "{{ nsxt.management_network.cidr.split('/')[0] }}"
            static_ip_ranges:
              - range:
                  begin:
                    type: "{{ nsxt.management_network.type }}"
                    addr: "{{ nsxtSegmentMgt.cidr.split('/')[0].split('.')[0] }}.{{ nsxtSegmentMgt.cidr.split('/')[0].split('.')[1] }}.{{ nsxtSegmentMgt.cidr.split('/')[0].split('.')[2] }}.{{ nsxt.management_network.ipStartPool }}"
                  end:
                    type: "{{ nsxt.management_network.type }}"
                    addr: "{{ nsxtSegmentMgt.cidr.split('/')[0].split('.')[0] }}.{{ nsxtSegmentMgt.cidr.split('/')[0].split('.')[1] }}.{{ nsxtSegmentMgt.cidr.split('/')[0].split('.')[2] }}.{{ nsxt.management_network.ipEndPool }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.network_vip.cidr is defined
        - nsxt.network_vip.ipStartPool is defined
        - nsxt.network_vip.ipEndPool is defined

    - name: Update Mgmt Network - NSXT
      avi_network:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.name }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        avi_api_patch_op : add
        avi_api_update_method: patch
        uuid: "{{ networkMgtUuid | default(omit) }}"
        name: "{{ nsxt.management_network.name }}"
        dhcp_enabled: "{{ nsxt.management_network.dhcp_enabled | default(omit) }}"
        exclude_discovered_subnets: "{{ nsxt.management_network.exclude_discovered_subnets | default(omit) }}"
        vcenter_dvs: "{{ nsxt.management_network.vcenter_dvs | default(omit) }}"
        configured_subnets: "{{ configured_subnets_mgmt | default(omit) }}"
      when:
        - nsxt.management_network.cidr is defined
        - nsxt.management_network.ipStartPool is defined
        - nsxt.management_network.ipEndPool is defined
        - nsxt.management_network.name is defined
        - nsxt.name is defined
      tags:
        - cloud

    - name: get Network details - NSXT
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        timeout: 300
        path: network
        params:
          page_size: -1
      register: networkOutput
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt is defined

    - name: Retrieve Network Vip Uuid  - NSXT
      set_fact:
        networkVipUuid: "{{ item.uuid }}"
      loop: "{{ networkOutput.obj.results }}"
      loop_control:
        label: "{{ item.name }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt is defined
        - item.name == nsxt.network_vip.name

    - name: Set IP details of Vip Network - NSXT
      set_fact:
        configured_subnets_vip:
          - prefix:
              mask: "{{ nsxt.network_vip.cidr.split('/')[1] }}"
              ip_addr:
                type: "{{ nsxt.network_vip.type }}"
                addr: "{{ nsxt.network_vip.cidr.split('/')[0] }}"
            static_ip_ranges:
              - range:
                  begin:
                    type: "{{ nsxt.network_vip.type }}"
                    addr: "{{ nsxtSegmentVip.cidr.split('/')[0].split('.')[0] }}.{{ nsxtSegmentVip.cidr.split('/')[0].split('.')[1] }}.{{ nsxtSegmentVip.cidr.split('/')[0].split('.')[2] }}.{{ nsxt.network_vip.ipStartPool }}"
                  end:
                    type: "{{ nsxt.network_vip.type }}"
                    addr: "{{ nsxtSegmentVip.cidr.split('/')[0].split('.')[0] }}.{{ nsxtSegmentVip.cidr.split('/')[0].split('.')[1] }}.{{ nsxtSegmentVip.cidr.split('/')[0].split('.')[2] }}.{{ nsxt.network_vip.ipEndPool }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.network_vip.cidr is defined
        - nsxt.network_vip.ipStartPool is defined
        - nsxt.network_vip.ipEndPool is defined

    - name: set vrf Vip - NSXT
      set_fact:
        vrfNsxt: "/api/vrfcontext/?name={{ nsxt.network_vip.tier1 }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - nsxt.network_vip.tier1 is defined

    - name: Update Vip Network - NSXT
      avi_network:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.name }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        avi_api_patch_op : add
        avi_api_update_method: patch
        uuid: "{{ networkVipUuid | default(omit) }}"
        name: "{{ nsxt.network_vip.name }}"
        dhcp_enabled: "{{  nsxt.network_vip.dhcp_enabled | default(omit) }}"
        exclude_discovered_subnets: "{{  nsxt.network_vip.exclude_discovered_subnets | default(omit) }}"
        vcenter_dvs: "{{  nsxt.network_vip.vcenter_dvs | default(omit) }}"
        configured_subnets: "{{ configured_subnets_vip | default(omit) }}"
        vrf_context_ref: "{{ vrfNsxt | default(omit) }}"
      register: networkOutput
      when:
        - nsxt.network_vip.cidr is defined
        - nsxt.network_vip.ipStartPool is defined
        - nsxt.network_vip.ipEndPool is defined
        - nsxt.name is defined
        - nsxt.network_vip.name is defined
      tags:
        - cloud

    - name: Create Avi IPAM - NSXT
      avi_ipamdnsproviderprofile:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        internal_profile:
          usable_networks:
            - nw_ref: "/api/network/{{ networkOutput.obj.uuid | default(networkVipUuid) }}"
        name: "{{ ipam.name | default('ipam-avi-nsxt') }}"
        type: IPAMDNS_TYPE_INTERNAL
      when:
        - nsxt.network_vip.name is defined
      tags:
        - cloud

    - pause:
        minutes: 1
      when:
        - nsxt is defined
      tags:
        - cloud
        - nsxtApi

    - name: Update vrf with default route for VIP network
      avi_vrfcontext:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        avi_api_patch_op : add
        avi_api_update_method: patch
        cloud_ref: "/api/cloud/?name={{ nsxt.name }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        name: "{{ nsxt.network_vip.tier1 }}"
        static_routes:
          - prefix:
              ip_addr:
                addr: "0.0.0.0"
                type: "{{ nsxt.network_vip.type | default('V4') }}"
              mask: "0"
            next_hop:
              addr: "{{ nsxtSegmentVip.cidr.split('/')[0].split('.')[0] }}.{{ nsxtSegmentVip.cidr.split('/')[0].split('.')[1] }}.{{ nsxtSegmentVip.cidr.split('/')[0].split('.')[2] }}.{{ nsxt.network_vip.gateway | default('1') }}"
              type: "{{ nsxt.network_vip.type | default('V4') }}"
            route_id: "1"
      when:
        - nsxt.name is defined
        - nsxt.network_vip.tier1 is defined
      tags:
        - cloud

    - name: Update Avi Cloud for NSXT
      avi_cloud:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ nsxt.name }}"
        vtype: CLOUD_NSXT
        nsxt_configuration:
          nsxt_url: "{{ nsxt.server }}"
          transport_zone: "{{ nsxtTransportZoneId.stdout }}"
          # site_id: default
          # enforcementpoint_id: default
          # domain_id: default
          management_segment:
            tier1_lr_id: "{{ nsxtTier1sMgt.id }}"
            segment_id: "{{ nsxtSegmentMgt.id }}"
          tier1_segment_config:
            segment_config_mode: TIER1_SEGMENT_MANUAL
            manual:
              tier1_lrs:
                - tier1_lr_id: "{{ nsxtTier1sVip.id }}"
                  segment_id: "{{ nsxtSegmentVip.id }}"
          #automate_dfw_rules: false
          nsxt_credentials_ref: "/api/cloudconnectoruser/{{ nsxtUserOutput.obj.uuid }}"
        dhcp_enabled: "{{ nsxt.dhcp_enabled }}"
        dns_provider_ref: "/api/ipamdnsproviderprofile/?name={{ nsxt.dns_provider_ref | default('dns-avi') }}"
        ipam_provider_ref: "/api/ipamdnsproviderprofile/?name={{ nsxt.ipam_provider_ref | default('ipam-avi-nsxt') }}"
        se_group_template_ref: "/api/serviceenginegroup?name=Default-Group"
        obj_name_prefix: "{{ nsxt.obj_name_prefix | default('AVINSXT') }}"
      when:
        - nsxt.name is defined
        - nsxt.server is defined
        - nsxt.dhcp_enabled is defined
      tags:
        - cloud
        - nsxtApi

    - name: Modify/Creating SE group - NSXT
      avi_serviceenginegroup:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.name }}"
        avi_api_update_method: put
        name: "{{ item.name }}"
        ha_mode: "{{ item.ha_mode | default('HA_MODE_SHARED') }}"
        min_scaleout_per_vs: "{{ item.min_scaleout_per_vs | default(omit) }}"
        buffer_se: "{{ item.buffer_se | default(omit) }}"
        extra_shared_config_memory: "{{ item.extra_shared_config_memory | default(omit) }}"
        vcenter_folder: "{{ item.vcenter_folder | default(omit) }}"
        vcpus_per_se: "{{ item.vcpus_per_se | default(omit) }}"
        memory_per_se: "{{ item.memory_per_se | default(omit) }}"
        disk_per_se: "{{ item.disk_per_se | default(omit) }}"
        realtime_se_metrics: "{{ item.realtime_se_metrics | default(omit) }}"
        auto_rebalance: "{{ item.auto_rebalance | default(omit) }}"
        auto_rebalance_interval: "{{ item.auto_rebalance_interval | default(omit) }}"
        auto_rebalance_criteria: "{{ item.auto_rebalance_criteria | default(omit) }}"
      loop: "{{ nsxt.serviceEngineGroup }}"
      loop_control:
        label: "Modifying SE group called {{ item.name }}"
      when:
        - nsxt.serviceEngineGroup is defined
        - nsxt.name is defined
      tags:
        - serviceEngineGroup