---
- hosts: localhost
  gather_facts: no

  vars_files:
    - "vars/params.yml"

#  vars:
#    my_pass: []

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Set variable avi_credentials
      set_fact:
        avi_credentials: >
                          {'api_version': "{{ avi_version }}",
                           'controller': "{{ controllerPrivateIps.0 }}",
                           'password': "{{ avi_password }}",
                           'username': "{{ avi_username }}"}
      tags:
        - creds
      when:
        - avi_version is defined
        - controllerPrivateIps is defined
        - avi_password is defined
        - avi_username is defined

    - name: Debug variable avi_credentials
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug

    - name: Update user admin password
      avi_useraccount:
        controller: "{{ avi_credentials.controller }}"
        username: "{{ avi_credentials.username }}"
        password: "{{ avi_credentials.password }}"
        old_password: 58NFaGDJm(PJH0G
        api_version: "{{ avi_credentials.api_version }}"
      ignore_errors: yes
      tags:
        - creds
      when:
        - controller.environment != "AWS"

    - name: Setting up Random password for users
      set_fact:
        my_pass: "{{ my_pass | default([]) +  [ lookup('password', '/dev/null length=4 chars==letters') + '_' + lookup('password', '/dev/null length=4 chars==letters') | upper ] }}"
      loop: "{{ aviUser }}"
      loop_control:
        label: "Configuring {{ item.name }}"
      when:
        - aviUser is defined
      tags:
        - creds
        - password

    # - debug:
    #     msg: "{{ item.0.name }}-{{ item.1 }}"
    #   loop: "{{ aviUser|zip(my_pass)|list }}"
    #   when: my_pass is defined

    - name: user creation
      avi_user:
        avi_credentials: "{{ avi_credentials }}"
        name: "{{ item.0.name }}"
        obj_username: "{{ item.0.name }}"
        obj_password: "{{ item.1 }}"
        access: "{{ item.0.access }}"
        user_profile_ref: "{{ item.0.user_profile_ref }}"
        is_active: "{{ item.0.is_active }}"
        is_superuser: "{{ item.0.is_superuser }}"
        default_tenant_ref: "{{ item.0.default_tenant_ref }}"
      loop: "{{ aviUser|zip(my_pass)|list }}"
      loop_control:
        label: "Configuring {{ item.0.name }}"
      when:
        - aviUser is defined
      tags:
        - creds

    - name: Change Avi Credentials - with Ansible user
      set_fact:
        avi_credentials: >
                          {'api_version': "{{ avi_version }}",
                           'controller': "{{ controllerPrivateIps.0 }}",
                          'password': "{{ my_pass.0 }}",
                          'username': "{{ aviUser.0.name }}"}
      tags:
        - creds

    - name: save json creds
      copy:
        content: '{"avi_credentials": {{ avi_credentials }} }'
        dest: "{{ controller.aviCredsJsonFile | default('~/.creds.json') }}"
      tags:
        - creds


    - name: Get main Cluster Information
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        http_method: get
        path: cluster
      register: clusterInfo
      tags:
        - cluster

    - name: Debug variable cluster uuid
      debug:
        msg: "{{ clusterInfo['obj'].uuid }}"
      tags:
        - debug


    - name: Set fact cluster_uuid
      set_fact:
        cluster_uuid: "{{ clusterInfo['obj'].uuid }}"
      when:
        - clusterInfo['obj'].uuid is defined

    - name: Configure Cluster object without ClusterIP - if cluster has been configured
      avi_cluster:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        nodes:
          - name: "{{ controllerPrivateIps.0 }}"
            ip:
              type: V4
              addr: "{{ controllerPrivateIps.0 }}"
          - name: "{{ controllerPrivateIps.1 }}"
            ip:
              type: V4
              addr: "{{ controllerPrivateIps.1 }}"
          - name: "{{ controllerPrivateIps.2 }}"
            ip:
              type: V4
              addr: "{{ controllerPrivateIps.2 }}"
        name: cluster-0-1
        uuid: "{{ cluster_uuid }}"
      when:
        - controller.cluster is true
        - controller.floating_ip is false
        - controller.environment == "VMWARE"
        - cluster_uuid is defined
      tags:
        - cluster

    - name: Configure Cluster object with ClusterIP - if cluster has been configured
      avi_cluster:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        nodes:
            - name: "{{ controllerPrivateIps.0 }}"
              ip:
                type: V4
                addr: "{{ controllerPrivateIps.0 }}"
            - name: "{{ controllerPrivateIps.1 }}"
              ip:
                type: V4
                addr: "{{ controllerPrivateIps.1 }}"
            - name: "{{ controllerPrivateIps.2 }}"
              ip:
                type: V4
                addr: "{{ controllerPrivateIps.2 }}"
        name: cluster-0-1
        uuid: "{{ cluster_uuid }}"
        virtual_ip:
            addr: "{{ controllerDefaultGateway | ipaddr(controllerFloatingIp) | ipv4('address') }}"
            type: V4
      when:
        - controller.cluster is true
        - controller.floating_ip is true
        - controller.environment == "VMWARE"
        - controllerDefaultGateway is defined
        - controllerFloatingIp is defined
        - cluster_uuid is defined
      tags:
        - cluster

    - name: sleep for 480 seconds and continue with play - if cluster has been configured
      wait_for: timeout=480
      when:
        - controller.cluster is true
        - controller.environment == "VMWARE"
      tags:
        - cluster

    # - name: Avi credentials
    #   debug:
    #     msg: "{{ avi_credentials }}"
    #   tags:
    #     - creds

#    - name: Configure Cluster without HA with Public Controller IP
#      avi_cluster:
#        avi_credentials: "{{ avi_credentials }}"
#        nodes:
#            - name: "{{ controllerPrivateIps.0 }}"
#              ip:
#                type: V4
#                addr: "{{ controllerPrivateIps.0 }}"
#              public_ip_or_name:
#                addr: "{{ controllerPublicIps.0 }}"
#                type: V4
#        name: cluster-0-1
#        uuid: "{{ cluster_uuid }}"
#      when:
#        - controller.enablePublicIP is defined
#      tags:
#        - cluster

#    - name: sleep for 180 seconds and continue with play - if Public Controller IP has been configured
#      wait_for: timeout=180
#      when:
#        - controller.enablePublicIP is defined
#      tags:
#        - cluster
#
#    - name: Wait for the Controller cluster to be up - if Public Controller IP has been configured
#      avi_api_session:
#        avi_credentials: "{{ avi_credentials }}"
#        http_method: get
#        timeout: 300
#        path: cluster/runtime
#      register: statusCluster
#      ignore_errors: yes
#      until:
#        - statusCluster.obj.cluster_state.state == "CLUSTER_UP_NO_HA" or statusCluster.obj.cluster_state.state == "CLUSTER_UP_HA_ACTIVE"
#      retries: 120
#      delay: 10
#      when:
#        - controller.enablePublicIP is defined
#      tags:
#        - cluster

#    - name: Change Avi Credentials if cluster config has been done - with floating cluster IP - if cluster has been configured
#      set_fact:
#        avi_credentials: >
#                          {'api_version': "{{ avi_version }}",
#                           'controller': "{{ controller.floatingIp }}",
#                           'password': "{{ my_pass.0 }}",
#                           'username': "{{ aviUser.0.name }}"}
#      when:
#        - controller.cluster is true
#        - controller.floatingIp is defined
#        - controller.environment == "VMWARE"
#      tags:
#        - cluster