---
- hosts: localhost
  gather_facts: no

  vars_files:
    - "vars/params.yml"
    #- "vars/creds.json"

  vars:
    my_pass: []

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Register Dynamic Inventory list for the controller group
      shell: ansible-inventory -i /opt/ansible/inventory/aws_ec2.yaml --list | jq .aws_group_controller
      ignore_errors: no
      register: dynamicInventoryOutputJson
      when:
        - controller.environment == "AWS"
      tags:
        - creds

    - set_fact:
        dynamicInventoryOutput: "{{ dynamicInventoryOutputJson.stdout | from_json }}"
      when:
        - controller.environment == "AWS"
      tags:
        - creds

    - set_fact:
        dynamicInventoryControllerHosts: "{{ dynamicInventoryOutput | json_query('hosts') }}"
      when:
        - controller.environment == "AWS"
      tags:
        - creds

    - name: Debug
      debug:
        msg: "{{ lookup('dig', dynamicInventoryControllerHosts.0) }}"
      when:
        - controller.environment == "AWS"
      tags:
        - creds

    # - name: Register Dynamic Inventory list for the controller group
    #   shell: ansible-inventory -i /opt/ansible/inventory/gcp.yaml --list | jq .gcp_group_controller
    #   ignore_errors: no
    #   register: dynamicInventoryOutputJson
    #   when:
    #     - controller.environment == "GCP"
    #   tags:
    #     - creds
    #
    # - set_fact:
    #     dynamicInventoryOutput: "{{ dynamicInventoryOutputJson.stdout | from_json }}"
    #   when:
    #     - controller.environment == "GCP"
    #   tags:
    #     - creds
    #
    # - set_fact:
    #     dynamicInventoryControllerHosts: "{{ dynamicInventoryOutput | json_query('hosts') }}"
    #   when:
    #     - controller.environment == "GCP"
    #   tags:
    #     - creds
    #
    # - name: Debug
    #   debug:
    #     msg: "{{ dynamicInventoryControllerHosts.0 }}"
    #   when:
    #     - controller.environment == "GCP"
    #   tags:
    #     - creds

    - name: Register JSON variables for credentials and cluster
      command: python3 python/generateJson.py ../hosts
      ignore_errors: no
      register: outputJson
      tags:
        - creds
      when:
        - controller.environment == "VMWARE"

    - set_fact:
        outputRaw: "{{ outputJson.stdout | from_json }}"
      tags:
        - creds
      when:
        - controller.environment == "VMWARE"

    - set_fact:
        avi_credentials: >
                          {'api_version': "{{ controller.version }}",
                           'controller': "{{ outputRaw | json_query('controller') }}",
                           'password': "{{ controller.password }}",
                           'username': "{{ controller.username }}"}
      tags:
        - creds
      when:
        - controller.environment == "VMWARE"

    - set_fact:
        avi_credentials: >
                          {'api_version': "{{ controller.version }}",
                           'controller': "{{ lookup('dig', dynamicInventoryControllerHosts.0) }}",
                           'password': "{{ controller.password }}",
                           'username': "{{ controller.username }}"}
      tags:
        - creds
      when:
        - controller.environment == "AWS"

    - set_fact:
        avi_credentials: >
                          {'api_version': "{{ controller.version }}",
                           'controller': "{{ controllerIps.0 }}",
                           'password': "{{ controller.password }}",
                           'username': "{{ controller.username }}"}
      tags:
        - creds
      when:
        - controller.environment == "GCP"


    # - set_fact:
    #     avi_credentials: >
    #                       {'api_version': "{{ controller.name.split('-')[2] }}",
    #                        'controller': "{{ outputRaw | json_query('controller') }}",
    #                        'password': "{{ controller.password }}",
    #                        'username': "{{ controller.username }}"}
    #   tags:
    #     - creds
    #   when:
    #     - controller.environment == "AWS"

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - creds

    - name: Update user admin password
      avi_useraccount:
        controller: "{{ avi_credentials.controller }}"
        username: "{{ avi_credentials.username }}"
        password: "{{ avi_credentials.password }}"
        old_password: 58NFaGDJm(PJH0G
        api_version: "{{ avi_credentials.api_version }}"
      ignore_errors: yes
      tags:
        - creds
      when:
        - controller.environment == "VMWARE" or controller.environment == "GCP"

    - name: Setting up Random password for users
      set_fact:
        my_pass: "{{ my_pass  +  [ lookup('password', '/dev/null length=4 chars==letters') + '_' + lookup('password', '/dev/null length=4 chars==letters') | upper ] }}"
      loop: "{{ aviUser }}"
      loop_control:
        label: "Configuring {{ item.name }}"
      when: aviUser is defined
      tags:
        - creds
        - password

    # - debug:
    #     msg: "{{ item.0.name }}-{{ item.1 }}"
    #   loop: "{{ aviUser|zip(my_pass)|list }}"
    #   when: my_pass is defined

    - name: user creation
      avi_user:
        avi_credentials: "{{ avi_credentials }}"
        name: "{{ item.0.name }}"
        obj_username: "{{ item.0.name }}"
        obj_password: "{{ item.1 }}"
        access: "{{ item.0.access }}"
        user_profile_ref: "{{ item.0.user_profile_ref }}"
        is_active: "{{ item.0.is_active }}"
        is_superuser: "{{ item.0.is_superuser }}"
        default_tenant_ref: "{{ item.0.default_tenant_ref }}"
      loop: "{{ aviUser|zip(my_pass)|list }}"
      loop_control:
        label: "Configuring {{ item.0.name }}"
      when: aviUser is defined
      tags:
        - creds

    - name: Change Avi Credentials - with Ansible user
      set_fact:
        avi_credentials: >
                          {'api_version': "{{ controller.version }}",
                          'controller': "{{ outputRaw | json_query('controller') }}",
                          'password': "{{ my_pass.0 }}",
                          'username': "{{ aviUser.0.name }}"}
      tags:
       - creds
      when:
        - controller.environment == "VMWARE"

    - name: Change Avi Credentials - with Ansible user
      set_fact:
        avi_credentials: >
                          {'api_version': "{{ controller.version }}",
                           'controller': "{{ lookup('dig', dynamicInventoryControllerHosts.0) }}",
                          'password': "{{ my_pass.0 }}",
                          'username': "{{ aviUser.0.name }}"}
      tags:
        - creds
      when:
        - controller.environment == "AWS"

    - name: Change Avi Credentials - with Ansible user
      set_fact:
        avi_credentials: >
                          {'api_version': "{{ controller.version }}",
                           'controller': "{{ controllerIps.0 }}",
                          'password': "{{ my_pass.0 }}",
                          'username': "{{ aviUser.0.name }}"}
      tags:
        - creds
      when:
        - controller.environment == "GCP"

    - name: Retrieve IP fo follower controllers - if cluster has been configured
      command: python3 python/retrieveIpFollowers.py ../hosts
      ignore_errors: no
      when:
        - controller.count == 3
        - controller.floatingIp is defined
        - controller.environment == "VMWARE"
      register: outputJson
      tags:
        - cluster

    - name: Variable change - if cluster has been configured
      set_fact:
        outputRaw: "{{ outputJson.stdout | from_json }}"
      when:
        - controller.count == 3
        - controller.floatingIp is defined
        - controller.environment == "VMWARE"
      tags:
        - cluster

    # - name: Debug
    #   debug:
    #     msg: "{{ outputRaw | json_query('controllerFollowerOne') }}"
    #   when:
    #     - controller.count == 3
    #     - controller.floatingIp is defined
    #   tags:
    #     - cluster
    #
    # - name: Debug
    #   debug:
    #     msg: "{{ outputRaw | json_query('controllerFollowerTwo') }}"
    #   when:
    #     - controller.count == 3
    #     - controller.floatingIp is defined
    #   tags:
    #     - cluster

    # - name: Get main Cluster Information - if cluster has been configured
    - name: Get main Cluster Information
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        # api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        path: cluster
      register: clusterInfo
      # when:
      #   - controller.count == 3
      #   - controller.floatingIp is defined
      #   - controller.environment == "VMWARE"
      tags:
        - cluster

    - name: Configure Cluster object with ClusterIP - if cluster has been configured
      avi_cluster:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        nodes:
            -
              name: "{{ avi_credentials.controller }}"
              ip:
                type: V4
                addr: "{{ avi_credentials.controller }}"
            -
              name: "{{ outputRaw | json_query('controllerFollowerOne') }}"
              ip:
                type: V4
                addr: "{{ outputRaw | json_query('controllerFollowerOne') }}"
            -
              name: "{{ outputRaw | json_query('controllerFollowerTwo') }}"
              ip:
                type: V4
                addr: "{{ outputRaw | json_query('controllerFollowerTwo') }}"
        name: controller.count
        uuid: "{{ clusterInfo['obj'].uuid }}"
        virtual_ip:
            addr: "{{ controller.floatingIp }}"
            type: V4
      when:
        - controller.count == 3
        - controller.floatingIp is defined
        - controller.environment == "VMWARE"
      tags:
        - cluster

    - name: sleep for 300 seconds and continue with play - if cluster has been configured
      wait_for: timeout=300
      when:
        - controller.count == 3
        - controller.floatingIp is defined
        - controller.environment == "VMWARE"
      tags:
        - cluster

    # - name: Avi credentials
    #   debug:
    #     msg: "{{ avi_credentials }}"
    #   tags:
    #     - creds

    - name: Wait for the Controller cluster to finish - if cluster has been configured
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: cluster/status
      register: statusCluster
      ignore_errors: yes
      until:
        - statusCluster.obj.cluster_state.state == "CLUSTER_UP_HA_ACTIVE"
        - statusCluster.obj.node_states.0.state == "CLUSTER_ACTIVE"
        - statusCluster.obj.node_states.1.state == "CLUSTER_ACTIVE"
        - statusCluster.obj.node_states.2.state == "CLUSTER_ACTIVE"
      retries: 120
      delay: 10
      when:
        - controller.count == 3
        - controller.floatingIp is defined
        - controller.environment == "VMWARE"
      tags:
        - cluster

    - name: Troubleshoot cluster uuid
      debug:
        msg: "{{ clusterInfo['obj'].uuid }}"
      tags:
        - creds

    - name: Troubleshoot Public Controller IP
      debug:
        msg: "{{ controller.publicIp }}"
      when:
        - controller.publicIp is defined
      tags:
        - creds

    - name: Troubleshoot Private Controller IP
      debug:
        msg: "{{ controller.privateIp }}"
      when:
        - controller.privateIp is defined
      tags:
        - creds

    - name: Configure Cluster without HA with Public Controller IP
      avi_cluster:
        avi_credentials: "{{ avi_credentials }}"
        nodes:
            - name: "{{ controllerPrivateIps.0 }}"
              ip:
                type: V4
                addr: "{{ controllerPrivateIps.0 }}"
              public_ip_or_name:
                addr: "{{ controllerPublicIps.0 }}"
                type: V4
        name: cluster-0-1
        uuid: "{{ clusterInfo['obj'].uuid }}"
      when:
        - controller.enablePublicIP is defined
        - controller.publicIp is defined
        - controller.privateIp is defined
      tags:
        - cluster

    - name: sleep for 180 seconds and continue with play - if Public Controller IP has been configured
      wait_for: timeout=180
      when:
        - controller.publicIp is defined
      tags:
        - cluster

    - name: Wait for the Controller cluster to be up
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        # api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: cluster/runtime
      register: statusCluster
      ignore_errors: yes
      until:
        - statusCluster.obj.cluster_state.state == "CLUSTER_UP_NO_HA" or statusCluster.obj.cluster_state.state == "CLUSTER_UP_HA_ACTIVE"
      retries: 120
      delay: 10
      # when:
      #   - controller.count == 3
      #   - controller.floatingIp is defined
      #   - controller.environment == "VMWARE"
      tags:
        - cluster

    - name: Troubleshoot statusCluster
      debug:
        msg: "{{ statusCluster }}"
      when:
        - statusCluster is defined
      tags:
        - creds


    - name: Change Avi Credentials if cluster config has been done - with floating cluster IP - if cluster has been configured
      set_fact:
        avi_credentials: >
                          {'api_version': "{{ controller.version }}",
                           'controller': "{{ controller.floatingIp }}",
                           'password': "{{ my_pass.0 }}",
                           'username': "{{ aviUser.0.name }}"}
      when:
        - controller.count == 3
        - controller.floatingIp is defined
        - controller.environment == "VMWARE"
      tags:
        - cluster

    # - name: Updated Avi credentials
    #   debug:
    #     msg: "{{ avi_credentials }}"
    #   tags:
    #     - creds

    - name: save json creds
      copy:
        content: '{"avi_credentials": {{ avi_credentials }} }'
        dest: "../vars/creds.json"
      tags:
        - creds
