---
- hosts: controller,aws_group_controller,gcp_group_controller,azure_group_controller,meta-avi_controller
  gather_facts: no
  connection: local

  tasks:

    - name: "Wait for the portal to become active"
      uri:
        url: "https://{{ ansible_host }}/"
        validate_certs: no
        status_code: 200
      register: result
      until: result.status == 200
      retries: 200
      delay: 20
      tags:
        - check