---
- hosts: localhost
  connection: local

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Modify/Creating SE group
      avi_serviceenginegroup:
        cloud_ref: "/api/cloud/?name={{ avi_cloud.name | default('Default-Cloud') }}"
        avi_api_update_method: put
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        ha_mode: "{{ item.ha_mode | default('HA_MODE_SHARED') }}"
        min_scaleout_per_vs: "{{ item.min_scaleout_per_vs | default(omit) }}"
        buffer_se: "{{ item.buffer_se | default(omit) }}"
        extra_shared_config_memory: "{{ item.extra_shared_config_memory | default(omit) }}"
        vcenter_folder: "{{ item.vcenter_folder | default(omit) }}"
        vcpus_per_se: "{{ item.vcpus_per_se | default(omit) }}"
        memory_per_se: "{{ item.memory_per_se | default(omit) }}"
        disk_per_se: "{{ item.disk_per_se | default(omit) }}"
        realtime_se_metrics: "{{ item.realtime_se_metrics | default(omit) }}"
        auto_rebalance: "{{ item.auto_rebalance | default(omit) }}"
        auto_rebalance_interval: "{{ item.auto_rebalance_interval | default(omit) }}"
        auto_rebalance_criteria: "{{ item.auto_rebalance_criteria | default(omit) }}"
        instance_flavor: "{{ item.instance_flavor | default(omit) }}"
      when:
        - serviceEngineGroup is defined
        - item.realtime_se_metrics is defined
      loop: "{{ serviceEngineGroup }}"
      loop_control:
        label: "Modifying SE group called {{ item.name }}"
      tags:
        - serviceEngineGroup

    # - name: Updating SE group for auto-scale out group based on cpu
    #   avi_serviceenginegroup:
    #     cloud_ref: "/api/cloud/?name={{ avi_cloud.name | default('Default-Cloud') }}"
    #     avi_credentials: "{{ avi_credentials }}"
    #     api_version: "{{ avi_credentials.api_version }}"
    #     avi_api_patch_op : add
    #     avi_api_update_method: patch
    #     name: "{{ item.name }}"
    #     ha_mode: "{{ item.ha_mode | default('HA_MODE_SHARED') }}"
    #     min_scaleout_per_vs: "{{ item.min_scaleout_per_vs | default('2') }}"
    #     buffer_se: "{{ item.buffer_se | default('1') }}"
    #     extra_shared_config_memory: "{{ item.extra_shared_config_memory | default('0') }}"
    #     vcenter_folder: "{{ item.vcenter_folder | default('se') }}"
    #     vcpus_per_se: "{{ item.vcpus_per_se | default('2') }}"
    #     memory_per_se: "{{ item.memory_per_se | default('4096') }}"
    #     disk_per_se: "{{ item.disk_per_se | default('25') }}"
    #     auto_rebalance: "{{ item.auto_rebalance | | default(omit) }}"
    #     auto_rebalance_interval: "{{ item.auto_rebalance_interval | default(omit) }}"
    #     auto_rebalance_criteria: "{{ item.auto_rebalance_criteria | default(omit) }}"
    #   when:
    #     - serviceEngineGroup is defined
    #     - item.auto_rebalance is defined
    #     - item.auto_rebalance_interval is defined
    #     - item.auto_rebalance_criteria is defined
    #     - avi_cloud.vtype == 'CLOUD_VCENTER'
    #   loop: "{{ serviceEngineGroup }}"
    #   loop_control:
    #     label: "Modifying SE group called {{ item.name }}"
    #   tags:
    #     - serviceenginegroup
