---
- hosts: localhost
  connection: local

  # vars_files:
  #   - "vars/params.yml"

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug

    - name: Define vip data for AZURE
      set_fact:
        vipAzure: "{{ vipAzure | default([]) + [{ 'vip_id': my_idx, 'auto_allocate_floating_ip': 'true', 'auto_allocate_ip': 'true', 'avi_allocated_fip': 'true', 'ipam_network_subnet': {'subnet_uuid': item.vip_network_id, 'subnet': {'mask': item.vip_network_cidr.split('/')[1], 'ip_addr': {'type': item.type, 'addr': item.vip_network_cidr.split('/')[0]}}}}] }}"
      loop: "{{ azureSubnets.vip }}"
      loop_control:
        index_var: my_idx
      when:
        - azure is defined
        - azureSubnets.vip is defined
      tags:
        - vsVip
        - vsDns
        - vs

    - name: Debug VIP data for Azure
      debug:
        msg: "{{ vipAzure }}"
      when:
        - azure is defined
        - azureSubnets.vip is defined
      tags:
        - debug

    - name: Create vsvip for http VS (Azure)
      avi_vsvip:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "vsvip-{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ item.cloud_ref | default('Default-Cloud') }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        dns_info:
          - fqdn: "{{ item.dns_info.0.fqdn | default(item.name + '.' + domain.name) }}"
            type: "{{ item.dns_info.0.type | default('DNS_RECORD_A') }}"
        vip: "{{ vipAzure }}"
      loop: "{{ avi_virtualservice.http }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - avi_virtualservice.http is defined
        - item.cloud_ref == "cloudAzure"
      tags:
        - vsvip
        - vsHttp
        - vs

    - name: Create vsvip for dns VS (Azure)
      avi_vsvip:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "vsvip-{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ item.cloud_ref | default('Default-Cloud') }}"
        tenant_ref: "/api/tenant?name={{ tenant_ref | default('admin') }}"
        dns_info:
          - fqdn: "{{ item.dns_info.0 | default(item.name + '.' + domain.name) }}"
            type: "{{ item.dns_info.0.type | default('DNS_RECORD_A') }}"
        vip: "{{ vipAzure }}"
      loop: "{{ avi_virtualservice.dns }}"
      when:
        - avi_virtualservice.dns is defined
        - azure is defined
      tags:
        - vsvip
        - vs
