---
- hosts: localhost
  connection: local

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug

    - name: Define vip data for NoAccess
      set_fact:
        vipNoAccessVmware:
          - ipam_network_subnet:
              network_ref: "{{ listNetworkUuid.0 | default('Null') }}"
              subnet:
                mask: "{{ network.cidr.split('/')[1] }}"
                ip_addr:
                  type: "{{ network.type | default('V4') }}"
                  addr: "{{ network.cidr.split('/')[0] }}"
            avi_allocated_fip: true
            auto_allocate_ip: true
            auto_allocate_floating_ip: true
      when:
        - no_access is defined
        - network.cidr is defined
        - listNetworkUuid is defined

    - name: Create vsvip for http VS for NoAccess
      avi_vsvip:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "vsvip-{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ item.cloud_ref | default('Default-Cloud') }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        dns_info:
          - fqdn: "{{ item.dns_info.0.fqdn | default(item.name + '.' + domain.name) }}"
            type: "{{ item.dns_info.0.type | default('DNS_RECORD_A') }}"
        vip: "{{ vipNoAccessVmware }}"
      loop: "{{ avi_virtualservice.http }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - avi_virtualservice.http is defined
        - item.cloud_ref == "cloudNoAccess"
      tags:
        - vsvip
        - vsHttp
        - vs

    - name: Create vsvip for dns VS for NoAccess
      avi_vsvip:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "vsvip-{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ item.cloud_ref | default('Default-Cloud') }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        dns_info:
          - fqdn: "{{ item.dns_info.0.fqdn | default(item.name + '.' + domain.name) }}"
            type: "{{ item.dns_info.0.type | default('DNS_RECORD_A') }}"
        vip: "{{ vipNoAccessVmware }}"
      loop: "{{ avi_virtualservice.dns }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - avi_virtualservice.dns is defined
        - item.cloud_ref == "cloudNoAccess"
      tags:
        - vsVip
        - vsDns
        - vs
