---
- hosts: localhost
  connection: local
  gather_facts: no

  # vars:
  #   zones: []

  vars_files:
    - "vars/params.yml"

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ item.0.cloud_ref }}"
      with_nested:
        - "{{ vstest.http }}"
        - "{{ awsZones | zip(awsSubnetAviVsCidrs, awsSubnetAviVsIds) | list }}"
      when:
        - item.0.cloud_ref == 'cloudAws'


        # zones: "{{ zones }} + ['mgmt_network_uuid': {{ item.0 }}, 'availability_zone': {{ item.1 }}, 'mgmt_network_name': {{ item.2 }} ]"


    - set_fact:
        vipAws: "{{ vipAws | default([]) + [{ 'auto_allocate_floating_ip': 'true', 'auto_allocate_ip': 'true', 'avi_allocated_fip': 'true', 'subnet': {'ipam_network_subnet': {'subnet_uuid': item.3, 'subnet': {'mask': item.2.split('/')[1], 'type': 'V4', 'addr': item.2.split('/')[0] }}}}] }}"
      with_nested:
        - "{{ vstest.http }}"
        - "{{ awsZones | zip(awsSubnetAviVsCidrs, awsSubnetAviVsIds) | list }}"
      when:
        - item.0.cloud_ref == 'cloudAws'
      # loop: "{{ awsZones | zip(awsSubnetAviVsCidrs, awsSubnetAviVsIds) | list }}"
      # when:
      #   - aws is defined


    - name: Debug
      debug:
        msg: "{{ vipAws }}"
      when:
        - aws is defined
