---
- hosts: aws_group_controller
  gather_facts: no
  become_user: root
  become_method: sudo
  vars:
    ansible_ssh_user: admin

  tasks:

    - name: Setting up admin password
      command: "{{ item }}"
      ignore_errors: no
      tags:
        - admin
      with_items:
        - sudo /opt/avi/scripts/initialize_admin_user.py --password "{{ avi_password }}"
      when:
        - controller.environment == "AWS"
